### PR TITLE
efi: add sbatlevel for shim from 24.04

### PR DESCRIPTION
**Pull request by valentindavid**
Note, this is for the uc22 branch.

### CODE REVIEW

**Comment by julian-klode** [comment]
I suppose also add `2024010900` level `shim,4\ngrub,3\ngrub.debian,4\n`; I just bumped the latest level in shim to a newer one, so this will popup eventually in shim builds, albeit in the shim we have now it is the latest policy.

But then again why not actually also support the latest policy. I updated it yesterday upstream to 2024040900
"shim,4\ngrub,4\ngrub.peimage,2\n"

**Comment by valentindavid** [comment]
It is going to be a big policy generated...

To be sure I understood, I need to add those?

* `sbat,1,2024010900\nshim,4\ngrub,3\ngrub.debian,4\n`
* `sbat,1,2024040900\nshim,4\ngrub,4\ngrub.peimage,2\n`

**Comment by valentindavid** [comment]
@julian-klode I have added the expected values you said. Could you verify them?

**Review by pedronis — APPROVED** [review]
thanks

**Comment by valentindavid** [comment]
I cannot merge. Whoever has that power should do it. Thank you.

**Review by chrisccoulson — APPROVED** [review]

**Comment by chrisccoulson** [comment]
I've approved this. I'm very glad we implemented support for nested PolicyORs because we're definitely going to be using them with this :)

**Pull request merged**
